spring:
  application:
    name: school-manager-backend
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=School;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:database/migration
logging:
  level:
    org.flywaydb: trace
    org.springframework.jdbc: trace
tokens:
  access:
    lifetime: 15m
    secret-key: '{"kty":"oct","k":"COlAdHmlpjs6vNscfaEIpnMquBy2HUeVYZgrLW7h0VQwvQpN1Xe1iixfS2UqJC7r"}'
  refresh:
    lifetime: 7d
    secret-key: '{"kty":"oct","k":"1bRe3qVIqtgRHFYCf1cItv9qktUnLLXK"}'
